CREATE TABLE Sheets (Id INTEGER PRIMARY KEY AUTOINCREMENT , Name TEXT, UserId INT);
CREATE TABLE Records(Id INTEGER PRIMARY KEY AUTOINCREMENT , SheetId INT, Event TEXT, Time INT);
CREATE TABLE Users(Id INTEGER PRIMARY KEY AUTOINCREMENT , Username TEXT, Password TEXT);